development: &default
  adapter: mysql
  database: shoulda_development
  username: root
  pool: 5
  timeout: 5000

test: &TEST
  <<: *default
  database: shoulda_test
  username: root
  min_messages: warning
